Add project files
vladanvi99/capstone-project-one pull request #1
Opened 2021-06-29 14:06 UTC by vladanvi99

In this pull request, I will add project HTML, CSS, and JS files.

2021-06-29 18:15 UTC, vichuge requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your README and PR message are descriptive ✔️

## Aspects to improve ♻️

- [ ] On video presentation, I invite you to add a highlight about a piece of the code you find interesting or proud to make.
- Again, I love you design, but according to given template, it has a lot of things to improve:
- [ ] The pages should look almost identical to the original design, outside the content differences.
- [ ] The pages use the exact same colors, for text, backgrounds, borders, etc, from the original design.
- Basic color swatch: #272A31, #EC5242, #D3D3D3
- [ ] The pages use the same fonts or similar fonts from the original design.
- Fonts used originally: Cocogoose, Lato
- [ ] All page elements have similar spacing, borders, shadows, and paddings to the original design.

| original | your design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/20563252/123845758-2cbd3680-d8da-11eb-9c25-230a73321a81.png) | ![image](https://user-images.githubusercontent.com/20563252/123845874-524a4000-d8da-11eb-9787-53e8a9901e97.png) |
| ![image](https://user-images.githubusercontent.com/20563252/123845948-6726d380-d8da-11eb-9927-4be52120c8fe.png) | ![image](https://user-images.githubusercontent.com/20563252/123845983-7279ff00-d8da-11eb-9d41-82143834f9ee.png) |
| ![image](https://user-images.githubusercontent.com/20563252/123846038-7efe5780-d8da-11eb-8df6-91a91a5ab995.png) | ![image](https://user-images.githubusercontent.com/20563252/123846091-90476400-d8da-11eb-9829-bb19d88bd6cd.png) |

- [ ] The form section is not on the template, I kindly invite you to remove it.
![image](https://user-images.githubusercontent.com/20563252/123846212-b2d97d00-d8da-11eb-9dac-87fc313f39c7.png)

- [ ] Check the comments under the review.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 5 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-29 18:15 UTC, vichuge commented on README.md
> +- etc
- [ ] The README contains an "Acknowledgements" section or similar that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/). 🐶

2021-06-29 18:15 UTC, vichuge commented on README.md
> +This project is [MIT](./MIT.md) licensed.
- [ ] The license should be [Creative Commons License](https://creativecommons.org/licenses/) in place for MIT. 🐱

2021-06-29 18:15 UTC, vichuge commented on README.md
> +No Live Preview
- [ ] Please, add a Live demo made with GitHub pages on your readme file. Configure it to use the branch where you're working now (you can do it con the configuration section on a project on GitHub page). 🐦

2021-06-29 18:15 UTC, vichuge commented on about.html
> +                    <img src="./images/global/menu-toggler.svg" alt="open-mobile-menu">
- [ ] I invite you to use another icon, a burger icon are 3 horizontal lines. Use the burger icon is more understandable for the most part users. If you want to have more info about burger icon [check this link](https://en.wikipedia.org/wiki/Hamburger_button). 🐊 
![image](https://user-images.githubusercontent.com/20563252/123841328-0648cc80-d8d5-11eb-8b22-af036b9e6975.png)

2021-06-29 18:15 UTC, vichuge commented on about.html
> +            <nav>
- [ ] The navbar should be separate in both, top dark bar and the bottom white bar. Your design is some! now I kindly invite you to change this and other details more about the [given design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015). 🐤 
![image](https://user-images.githubusercontent.com/20563252/123841675-75bebc00-d8d5-11eb-8f2b-722ab1fba09c.png)

2021-06-29 18:15 UTC, vichuge commented on about.html
> +        </footer>
- [ ] The footer should be more like the [given design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015). 🦊 
- A logo center to the left and text on the right side.
- Dark color for desktop
![image](https://user-images.githubusercontent.com/20563252/123842275-35137280-d8d6-11eb-8ef3-5378f134abf4.png)

- White color for mobile
![image](https://user-images.githubusercontent.com/20563252/123842346-49576f80-d8d6-11eb-8dda-2692de93d86d.png)

2021-07-01 15:41 UTC, mricanho approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @vladanvi99🔥 

You did excellent work as always, nothing more to add here!

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-01 16:06 UTC, merged